<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Created at' => 'Пользователь Создан в',
  'Deleted' => 'удаленный',
  'Email' => 'Электронная почта',
  'First Name' => 'Имя',
  'Invitation use' => 'Приглашение пользовать',
  'Last Name' => 'Фамилия',
  'Last visited at' => 'Последнее посещение',
  'Loging page' => 'Loging страницы',
  'New password' => 'Новый пароль',
  'Password' => 'пароль',
  'People' => 'люди',
  'Person' => 'человек',
  'PersonId' => '',
  'Phone' => 'телефон',
  'Reseted Your password for' => 'Сброшена Ваш пароль для',
  'This user\'s email address already exists.' => 'Этот адрес электронной почты уже существует.',
  'User' => 'пользователь',
  'User name' => 'имя пользователя',
  'Welcome to' => 'Добро пожаловать',
  'You have been invited by {user} to become a user of system {system}' => 'Вы были приглашены {пользователь}, чтобы стать пользователем системы {системы}',
  'Your password reseted by {user} for system {system}' => 'Ваш пароль сбрасывается через {пользователь} для системы {системы}',
  'relation.CcucUserCompanies' => '',
  'relation.User' => '',
  'tooltip.deleted' => '',
  'tooltip.email' => '',
  'tooltip.first_name' => '',
  'tooltip.id' => '',
  'tooltip.last_name' => '',
  'tooltip.phone' => '',
  'tooltip.user_id' => '',
);