<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Created at' => '',
  'Deleted' => '',
  'Email' => '',
  'First Name' => '',
  'Invitation use' => '',
  'Last Name' => '',
  'Last visited at' => '',
  'Loging page' => '',
  'New password' => '',
  'Password' => '',
  'People' => '',
  'Person' => '',
  'PersonId' => '',
  'Phone' => '',
  'Reseted Your password for' => '',
  'This user\'s email address already exists.' => '',
  'User' => '',
  'User name' => '',
  'Welcome to' => '',
  'You have been invited by {user} to become a user of system {system}' => '',
  'Your password reseted by {user} for system {system}' => '',
  'relation.CcucUserCompanies' => '',
  'relation.User' => '',
  'tooltip.deleted' => '',
  'tooltip.email' => '',
  'tooltip.first_name' => '',
  'tooltip.id' => '',
  'tooltip.last_name' => '',
  'tooltip.phone' => '',
  'tooltip.user_id' => '',
);
