<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Created at' => 'Lietotajs izveidots',
  'Deleted' => 'Dzēsts',
  'Email' => 'Epasts',
  'First Name' => 'Vārds',
  'Invitation use' => 'Uzaicināts lietot',
  'Last Name' => 'Uzvārds',
  'Last visited at' => 'Pēdējā vizīte',
  'Loging page' => 'Autorizācijas lapa',
  'New password' => 'Jauna parole',
  'Password' => 'Parole',
  'People' => 'Personas',
  'Person' => 'Persona',
  'PersonId' => '',
  'Phone' => 'Telefons',
  'Reseted Your password for' => 'Jūsu parole atstatīta priekš',
  'This user\'s email address already exists.' => 'šads epasts jau ir reģistrēts',
  'User' => 'Leitotajs',
  'User name' => 'Lietotaja vārds',
  'Welcome to' => 'Laipni lūgti',
  'You have been invited by {user} to become a user of system {system}' => 'Jūs uziacinājis {user} kļūt par sistēmas {system} lietotāju',
  'Your password reseted by {user} for system {system}' => 'Jūsu sistēmas {system} paroli atstatīja {user}',
  'relation.CcucUserCompanies' => '',
  'relation.User' => '',
  'tooltip.deleted' => '',
  'tooltip.email' => '',
  'tooltip.first_name' => '',
  'tooltip.id' => '',
  'tooltip.last_name' => '',
  'tooltip.phone' => '',
  'tooltip.user_id' => '',
);